### PR TITLE
Add PHP 8.0 build

### PR DESCRIPTION
**Pull request by andrewmy**
Tried this with enqueue, appears to work.﻿

### CODE REVIEW

**Comment by makasim** [comment]
Build&pushed 8.0 https://hub.docker.com/layers/134572617/makasim/nginx-php-fpm/8.0-latest-all-exts/images/sha256-7475e2af537afa0657c8cad5e7705b091cd7e9f9349bcda818bc2ade7e1cd1cd?context=explore

**Comment by andrewmy** [comment]
Thanks! Could you also please tag `7.3-latest-all-exts`?

**Comment by andrewmy** [comment]
@makasim now that I think about it, it doesn't make much sense to have "latest" for both php versions.
How about tagging:
- `8.0`
- `8.0-all-exts`
- `7.3`
- `7.3-all-exts`
- `latest` = `8.0`
- `latest-all-exts` = `8.0-all-exts`

WDYT?

**Comment by makasim** [comment]
Make sense. What should I do ?

**Comment by andrewmy** [comment]
See https://github.com/makasim/docker-nginx-php-fpm/pull/3

**Pull request merged**
